// Generated file. Do not edit.
// This file is generated by the iFlutter

// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars
class AssetsRes {
  AssetsRes._();

  static const String PROJECT_NAME = 'flutterhero';
  static const String PROJECT_VERSION = '1.0.0+1';
  static const String RUNNING = 'assets/animation/running.json';
  static const String CONTAINER = 'assets/photos/container.png';
  static const String ONBOARDING1 = 'assets/photos/onboarding1.svg';
  static const String ONBOARDING2 = 'assets/photos/onboarding2.svg';
  static const String ONBOARDING3 = 'assets/photos/onboarding3.svg';
}
